with CTE AS (
select
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE (TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR (TO_TIMESTAMP(STARTED_AT)) AS HOUR_SARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('sat','sun')
  THEN 'WEEKEND'
  ELSE 'BUSINESSDAY'
  END AS DAYTYPE,
CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
    THEN 'Winter'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
    THEN 'Spring'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'Summer'
    ELSE 'Autum'
    END AS STATION_OF_YEAR
FROM 
{{ source('DEMO', 'BIKE') }}
WHERE STARTED_AT != 'started_at'
)
SELECT * FROM CTE