with CTE AS (
select
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE (TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR (TO_TIMESTAMP(STARTED_AT)) AS HOUR_SARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('sat','sun')
  THEN 'WEEKEND'
  ELSE 'BUSINESSDAY'
  END AS DAYTYPE,
 {{get_season('STARTED_AT')}} as station_of_yea
FROM 
{{ source('DEMO', 'BIKE') }}
WHERE STARTED_AT != 'started_at'
)
SELECT * FROM CTE